In [29]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [72]:
tf.__version__

'2.4.1'

In [73]:
data = pd.read_csv('Churn_Modelling.csv')


In [74]:
data.head()

RowNumber  CustomerId   Surname  CreditScore Geography  Gender  Age  \
0          1    15634602  Hargrave          619    France  Female   42   
1          2    15647311      Hill          608     Spain  Female   41   
2          3    15619304      Onio          502    France  Female   42   
3          4    15701354      Boni          699    France  Female   39   
4          5    15737888  Mitchell          850     Spain  Female   43   

   Tenure    Balance  NumOfProducts  HasCrCard  IsActiveMember  \
0       2       0.00              1          1               1   
1       1   83807.86              1          0               1   
2       8  159660.80              3          1               0   
3       1       0.00              2          0               0   
4       2  125510.82              1          1               1   

   EstimatedSalary  Exited  
0        101348.88       1  
1        112542.58       0  
2        113931.57       1  
3         93826.63       0  
4         79084.10       0

In [75]:
X = data.iloc[:, 3:-1].values
y = data.iloc[:, -1].values

In [76]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:,2]=le.fit_transform(X[:,2])

In [77]:
X

array([[619, 'France', 0, ..., 1, 1, 101348.88],
       [608, 'Spain', 0, ..., 0, 1, 112542.58],
       [502, 'France', 0, ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 0, ..., 0, 1, 42085.58],
       [772, 'Germany', 1, ..., 1, 0, 92888.52],
       [792, 'France', 0, ..., 1, 0, 38190.78]], dtype=object)

In [78]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct= ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [79]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [80]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [81]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train=sc.fit_transform(X_train)
X_test= sc.transform(X_test)

In [82]:
X

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [93]:
ann = tf.keras.models.Sequential()

In [94]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [95]:
ann.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))

In [96]:
ann.add(tf.keras.layers.Dense(units=8, activation='sigmoid'))

In [105]:
ann.add(tf.keras.layers.Dense(units=7, activation='sigmoid'))

In [106]:
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [107]:
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [108]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [109]:
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5398 - accuracy: 0.8044
Epoch 2/100
250/250 [==============================] - 0s 994us/step - loss: 0.4362 - accuracy: 0.7909
Epoch 3/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3907 - accuracy: 0.8070
Epoch 4/100
250/250 [==============================] - 0s 931us/step - loss: 0.3700 - accuracy: 0.8573
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3652 - accuracy: 0.8570
Epoch 6/100
250/250 [==============================] - 0s 931us/step - loss: 0.3559 - accuracy: 0.8586
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3672 - accuracy: 0.8480
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 0.3449 - accuracy: 0.8648
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3420 - accuracy: 0.8627
Epoch 10/100
250/250 [==============================] - 0s 994us/step - loss: 0.3421 

250/250 [==============================] - 0s 1ms/step - loss: 0.3308 - accuracy: 0.8652
Epoch 82/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3373 - accuracy: 0.8597
Epoch 83/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3197 - accuracy: 0.8692
Epoch 84/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3230 - accuracy: 0.8687
Epoch 85/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3300 - accuracy: 0.8651
Epoch 86/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3334 - accuracy: 0.8597
Epoch 87/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3311 - accuracy: 0.8651
Epoch 88/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3248 - accuracy: 0.8654
Epoch 89/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3435 - accuracy: 0.8601
Epoch 90/100
250/250 [==============================] - 0s 1ms/step - loss: 0.3313 - accuracy: 

In [110]:
print(ann.predict(sc.transform([[1.0, 0.0, 0.0,600,1,40,3,60000,2,1,1,50000 ]]))>0.5)

[[False]]


In [111]:
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [112]:
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
print(cm)
accuracy_score(y_test, y_pred)

[[1520   75]
 [ 209  196]]


0.858